export const SET_GROUP = "SET_GROUP";
export const SET_BOOKABLE = "SET_BOOKABLE";
export const TOGGLE_HAS_DETAILS = "TOGGLE_HAS_DETAILS";
export const NEXT_BOOKABLE = "NEXT_BOOKABLE";
export const FETCH_BOOKABLES_REQUEST = "FETCH_BOOKABLES_REQUEST";
export const FETCH_BOOKABLES_SUCCESS = "FETCH_BOOKABLES_SUCCESS";
export const FETCH_BOOKABLES_ERROR = "FETCH_BOOKABLES_ERROR";
